import random
from torch.utils.data import Dataset

class FrameDataset(Dataset):
    def __init__(self, frame_data):
        # frame_data is a list of tuples: (current_screen_data, action, next_screen_data, game_over)
        self.frame_data = frame_data

    def __len__(self):
        return len(self.frame_data)

    def __getitem__(self, idx):
        current_screen, action, next_screen, game_over = self.frame_data[idx]
        return current_screen, action, next_screen, game_over

    def clear(self):
        self.frame_data.clear()
    
    def generateFrameTrios(self, batch_size):
        real_frame_trios = [[]]
        random_frame_trios = [[]]
        fakeAction_frame_trios = [[]]
        for i in range(batch_size):
            # Get a random frame
            random_frame = self.frame_data[random.randint(0, len(self.frame_data) - 1)]
            random_frame1 = self.frame_data[random.randint(0, len(self.frame_data) - 1)]
            random_frame2 = self.frame_data[random.randint(0, len(self.frame_data) - 1)]
            # Get a random action
            random_action = random.randint(0, 1)
            # Get a random frame that was generated by the random action
            fakeAction_frame = self.frame_data[random.randint(0, len(self.frame_data) - 1)]
            real_frame_trios.append(random_frame)
            random_frame_trios.append([random_frame1, random_frame2, random_action])
            #TODO - add the action to the frame
            fakeAction_frame_trios.append(fakeAction_frame)
        return real_frame_trios, random_frame_trios, fakeAction_frame_trios